# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 14:19
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='autos', verbose_name='Imagenes')),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarios', models.CharField(max_length=18)),
                ('marca', models.CharField(choices=[('chevrolet', 'Chevrolet'), ('fiat', 'Fiat'), ('citroen', 'Citroen'), ('ford', 'Ford'), ('peugeot', 'Peugeot'), ('renault', 'Renault')], max_length=15)),
                ('version', models.CharField(max_length=20)),
                ('kilometraje', models.IntegerField()),
                ('combustible', models.CharField(choices=[('nafta', 'Nafta'), ('gnc', 'Gnc'), ('diesel', 'Diesel')], max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('fabricacion', models.IntegerField()),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Publicacion')),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='auto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.Auto', verbose_name='Auto'),
        ),
    ]
